### ISSUE TITLE
[Spike] Investigate desktop technologies

### ISSUE THREAD

**Issue by GurgenAvagyan** [3d-diploma-project/tetrahedron-desktop#4]
Investigate desktop technologies to use in our project:

- Make a brief summary of the selected technology
- Provide a list of pros and cons of the technology

**Comment by HappyMary16** [comment]
Closed this task as we are using Jira for task management.

Created Jira tasks for this activity:
https://getinfokhpi.atlassian.net/browse/TET-18
https://getinfokhpi.atlassian.net/browse/TET-19
