### ISSUE TITLE
Epic: desktop

### ISSUE THREAD

**Issue by ut5tw** [3d-diploma-project/tetrahedron-desktop#7]
### Figma design: [link](https://www.figma.com/design/aZ3zFLZUeyro32jMiVrMZM/desktop?node-id=0-1&t=fuIQGzSiyuVAjfFN-1)

- #4
- #6

**Comment by HappyMary16** [comment]
Closed the epic as we are going to use Jira for task management

Also "desktop" is a terrible name/scope of an epic. Epic cannot be created for the development of a whole program.
It must describe some part of the functionality, not everything.
